skedulr/config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  delete 'destroy_relation/:id', to: 'businesses#destroy_relation', as: :destroy_relation

  devise_for :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :shifts
  resources :businesses
  resources :employees
  resources :manager_employees, except: [:destroy]

  delete 'manager_employees/delete', to: 'manager_employees#manager_delete'

  get 'shifts/by_business/:business_id', to: 'shifts#get_shifts_by_business'
end

skedulr/app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :business_employee_relations
  has_many :businesses, through: :business_employee_relations #, optional: true
  has_many :shifts

  has_many :manager_employees, foreign_key: "manager_id", primary_key: "id"

  def is_manager?(business_id)
    ManagerEmployee.exists?(manager_id: self.id, business_id: business_id)
  end

  def has_manager?(business_id)
    ManagerEmployee.exists?(employee_id: self.id, business_id: business_id)
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

skedulr/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  include EmployeesHelper

  before_action :authenticate_employee!

  def index
    @employee = current_employee

    if @employee.first_name.blank? || @employee.last_name.blank?
      redirect_to edit_employee_path(@employee)
    elsif @employee.businesses.count
      @businesses = @employee.businesses
    else
      redirect_to businesses_path
    end

    session[:manager] = false
    session[:employee_id] = nil
    session[:current_business_id] = nil
  end

  def create
    @employee = current_employee
    @employee.update(employee_params)
  end

  def edit
    if session[:manager]
      @employee = Employee.find(params[:id])
    else
      @employee = current_employee
    end
  end

  def show
    @employee = current_employee
    @businesses = @employee.business
  end

  def update
    if session[:manager]
      @employee = Employee.find(params[:id])
    else
      @employee = current_employee
    end

    @employee.update(employee_params)

    redirect_to employees_path
  end

end

skedulr/app/helpers/employees_helper.rb
module EmployeesHelper
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :is_manager, :encrypted_password, :manager_table_id, business_ids: [])
  end
end

skedulr/app/views/employees/edit.html.erb
<%= form_for @employee do |f| %>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

skedulr/app/views/employees/index.html.erb
<h3>Hi <%= @employee.first_name %></h3>
<p>Which business would you like to look at your shifts for?</p>
<% for business in @businesses do %>
  <div>
    <p><%= business.name %></p>
    <ul>
      <% if @employee.is_manager?(business.id) %>
        <li>
          <%= link_to "View Business", business_path(business.id) %>
        </li>
      <% end %>
      <li>
        <%= link_to "View Shifts", shifts_path(shift: {business_id: business.id}) %>
      </li>
      <li>
        <%= link_to "Remove", destroy_relation_path(business.id), method: :delete%>
      </li>
    </ul>
  </div>
<% end %>
<%= link_to "Add business", businesses_path %>
<br>
<%= link_to "Edit employee profile", edit_employee_path(@employee) %>

skedulr/app/views/employees/show.html.erb
<h3><%= @managed_employee.full_name %>'s Shifts</h3>
<h5><%= @business.name %></h5>

<ul>
  <% @shifts.each do |shift| %>
  <li>
    <p> Start: <%= shift.start %> </p>
    <p> Stop: <%= shift.stop %> </p>
  </li>
  <% end %>
</ul>
<% if @current_employee.is_manager?(@business.id) %>
  <%= link_to "Create new shift", new_shift_path(shift: {business_id: @business.id}), class: "new_shift" %>
<% end %>
<br>
<%= link_to "Home", employees_path %>