skedulr/config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  delete 'destroy_relation/:id', to: 'businesses#destroy_relation', as: :destroy_relation

  devise_for :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :shifts
  resources :businesses
  resources :employees
  resources :manager_employees, except: [:destroy]

  delete 'manager_employees/delete', to: 'manager_employees#manager_delete'

  get 'shifts/by_business/:business_id', to: 'shifts#get_shifts_by_business'
end

skedulr/app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  include BusinessesHelper

  def index
    @businesses = Business.search(params[:term])
    @employee = current_employee
  end

  def create
    @business = Business.new(business_params)
    @business.save

    #Attach new business to current employee
    @employee = current_employee
    @relation = BusinessEmployeeRelation.new(employee_id: @employee.id, business_id: @business.id)
    @relation.save

    #Should probably test if the employee profile has been filled out to
    #determine where to redirect
    redirect_to employees_path
  end

  def new
    @business = Business.new
  end

  def edit
  end

  def update
    @employee = current_employee
    @business = Business.find(params[:id])
    if find_business_employee_relation(@business.id,@employee.id).empty?
      @employee.businesses << @business
    end

    redirect_to employees_path
  end

  def show
    @business = Business.find(params[:id])
    @employee = current_employee
    @employees = @business.employees
    @managers = @employees.select { |x| x.is_manager?(@business.id) }

    sorted_employees = @employees.partition do |employee|
                           ManagerEmployee.exists?(business_id: @business.id,
                                                   manager_id: @employee.id,
                                                   employee_id: employee.id) ||
                           employee.eql?(@employee)
                         end

    @managed_employees = sorted_employees[0]
    @employees = sorted_employees[1]

    session[:manager] = @employee.id
    session[:employee_id] = nil
    session[:current_business_id] = params[:id]
  end

  def destroy
    @business = Business.find(params[:id])

    @business.destroy

    redirect_to businesses_path
  end


  def destroy_relation
    @employee = current_employee
    @business = Business.find(params[:id])
    @relation = find_business_employee_relation(@business.id, @employee.id)

    BusinessEmployeeRelation.destroy(@relation.ids)

    redirect_to employees_path
  end

  private

  def find_business_employee_relation(business_id, employee_id)
    BusinessEmployeeRelation.where("business_id = ? AND employee_id = ?", business_id, employee_id)
  end
end

skedulr/app/helpers/businesses_helper.rb
module BusinessesHelper
  def business_params
    params.require(:business).permit(:name, :term, :employee_id, :id)
  end
end

skedulr/app/views/businesses/_business.html.erb
<%= form_for @business do |f| %>
  <p>
    Please enter your Business <%= f.label :name %>:
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

skedulr/app/views/businesses/edit.html.erb
<h3> Create new business </h3>

<%= render partial: 'business' %>

skedulr/app/views/businesses/index.html.erb
<%= link_to "Create New Business", new_business_path %> or
<p> Search for existing business </p>
<%= form_tag(businesses_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
<% for business in @businesses do %>
  <ul>
    <li>
      <%= business.name %>
      <%= link_to "Add", business_path(business.id), method: :put %>
      <%= link_to "Remove", business_path(business.id), method: :delete%>
    </li>
  </ul>
<% end %>

skedulr/app/views/businesses/new.html.erb
<%= form_for @business do |f| %>
  <p>
    Please enter your Business <%= f.label :name %>:
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

skedulr/app/views/businesses/show.html.erb
<h1><%= @business.name %></h1>
<h3>Managers</h3>
  <ul>
    <% @managers.each do |manager| %>
    <li>
      <%= manager.full_name %>
      <%= manager.id %>
    </li>
    <% end %>
  </ul>
<br>
<h3>Employees</h3>
  <ul>
    <% @managed_employees.each do |employee| %>
    <li>
      <%= link_to employee.full_name, shifts_path(employee: {id: employee.id}) %>
      <%= employee.id %>
      <% if employee.is_manager?(@business.id) %>
        <%= link_to "Edit Manager", new_manager_employee_path(employee: {id: employee.id}) %>
      <% else %>
        <%= link_to "Add as Manager", new_manager_employee_path(employee: {id: employee.id}) %>
      <% end %>
    </li>
    <% end %>

    <% @employees.each do |employee| %>
    <li>
      <%= employee.full_name %>
      <%= employee.id %>
      <% if !employee.is_manager?(@business.id) %>
        <%= link_to "Add as Manager", new_manager_employee_path(employee: {id: employee.id}) %>
      <% end %>
    </li>
    <% end %>
  </ul>
  <%= link_to "Home", employees_path %>