skedulr/config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  delete 'destroy_relation/:id', to: 'businesses#destroy_relation', as: :destroy_relation

  devise_for :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :shifts
  resources :businesses
  resources :employees
  resources :manager_employees, except: [:destroy]

  delete 'manager_employees/delete', to: 'manager_employees#manager_delete'

  get 'shifts/by_business/:business_id', to: 'shifts#get_shifts_by_business'
end

skedulr/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Skedulr</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", employee_path(@employee)%></li>
        <li><%= link_to "New Business", new_business_path %></li>
        <li><%= link_to "New Business", new_business_path %></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

skedulr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skedulr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="col-lg-12">
      <%= yield %>
    </div>
  </body>
</html>