skedulr/config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  delete 'destroy_relation/:id', to: 'businesses#destroy_relation', as: :destroy_relation

  devise_for :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :shifts
  resources :businesses
  resources :employees
  resources :manager_employees, except: [:destroy]

  delete 'manager_employees/delete', to: 'manager_employees#manager_delete'

  get 'shifts/by_business/:business_id', to: 'shifts#get_shifts_by_business'
end

skedulr/app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :employee
  # def generate_shift
  # end
end

skedulr/app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  include ShiftsHelper

  def index
    if session[:manager]
      session[:employee_id] ||= params[:employee][:id]
      @employee = Employee.find(session[:employee_id])
    else
      @employee = current_employee
    end

    @first_name = @employee.first_name

    if !session[:current_business_id]
      session[:current_business_id] = params[:shift][:business_id]
    end

    @business = Business.find(session[:current_business_id])

    @shifts = Shift.where(business_id: @business.id, employee_id: @employee.id)
  end

  def create
    shift_values = params[:shift]
    @shift = Shift.new(start: parse_date(shift_values[:start]), 
                       stop: parse_date(shift_values[:stop]),
                       employee_id: current_employee.id,
                       business_id: session[:current_business_id])

    if session[:manager]
      @shift.employee_id = session[:employee_id]
    else
      @shift.employee_id = current_employee.id
    end

    @shift.business_id = session[:current_business_id]
    if !@shift.save
      puts @shift.errors.full_messages
    end

    redirect_to shifts_path
  end

  def parse_date date
    DateTime.strptime(date, "%m/%d/%Y %l:%M %p")
  end

  def new
    @shift= Shift.new
    @shift.start = DateTime.now
    @shift.stop = DateTime.now
  end

  def edit
  end

  def get_shifts_by_business
    shift_data = Shift.where(employee_id: current_employee.id,
                             business_id: params[:business_id])
    render json: shift_data.pluck(:start, :stop)
  end
end

skedulr/app/helpers/shifts_helper.rb
module ShiftsHelper
  def shift_params
    params.require(:shift).permit(:start, :stop, :employee_id, :business_id)
  end
end

skedulr/app/views/shifts/_date.html.erb
<div class="form-group">
  <%= f.label name %>
  <div class='input-group date datetimepicker'>
    <%= f.text_field name, class: "form-control" %>
    <span class="input-group-addon">
      <span class="glyphicon glyphicon-calendar"></span>
    </span>
  </div>
</div>

skedulr/app/views/shifts/index.html.erb
<h1><%= @business.name %></h1>
<h3><%= @first_name %>'s Shifts</h3>
<span hidden id="hidden-business-id" data-business_id=<%= @business.id %>></span>

<div id="calender-container">
  <div id="calendar"></div>
</div>

<ul>
  <% @shifts.each do |shift| %>
  <li>
    <p> Start: <%= shift.start %> </p>
    <p> Stop: <%= shift.stop %> </p>
  </li>
  <% end %>
</ul>
<% if session[:manager]||@employee.is_manager?(@business.id) %>
  <%= link_to "Create new shift",
              new_shift_path(shift: {business_id: @business.id}),
              class: "new_shift" %>
<% end %>
<br>
<%= link_to "Back to profile", employees_path %>

skedulr/app/views/shifts/new.html.erb
<h1>Create new shift</h1>
<%= form_for @shift do |f| %>
  <div class="col-md-6">
    <%= render partial: "date", locals: {name: :start, f: f} %>
  </div>
  <div class="col-md-6">
    <%= render partial: "date", locals: {name: :stop, f: f} %>
  </div>
  <%= f.submit class: 'btn btn-success'%>
<% end %>